# -*- coding: utf-8 -*-
"""ELIZA Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ky36n9aPK_2_2Xj5rnM3G0CE5TQvBWQ1
"""

from google.colab import drive
drive.mount('/content/drive')

# Install the NLTK library
!pip install nltk

# Import NLTK and download the essential data packages
import nltk
nltk.download('punkt')
nltk.download('wordnet')

"""# This code is designed to run in Google Colab.
# It includes Colab-specific installation commands (!pip install) and mounts Google Drive if needed.
# Screenshots were taken from the Colab output area.

"""

import re
import random

class SimpleELIZA:
    def __init__(self):

        self.rules = [

            (r'my name is (.*)', [f"Nice to meet you, {{0}}. How can I help?",
                                  f"Hello {{0}}, tell me more."]),


            (r'i feel (.*)', [f"Why do you feel {{0}}?",
                              f"How long have you felt {{0}}?"]),


            (r'i am (.*)', [f"Why are you {{0}}?",
                            f"Does being {{0}} affect you much?"]),


            (r'i need (.*)', [f"Why do you need {{0}}?",
                              f"What would having {{0}} do for you?"]),


            (r'my mother (.*)', [f"Tell me more about your mother.",
                                 f"How does your mother make you feel?"]),


            (r'because (.*)', [f"Is that the real reason?",
                               f"Does that reason explain everything?"]),


            (r'i like (.*)', [f"Why do you like {{0}}?",
                              f"Tell me more about your liking of {{0}}."]),


            (r'i hate (.*)', [f"What makes you hate {{0}}?",
                              f"How does hating {{0}} affect you?"]),
        ]

        self.defaults = [
            "That's interesting. Please tell me more.",
            "I see. Can you elaborate?",
            "Why do you say that?"
        ]
        #

    def get_response(self, user_input):
        user_input = user_input.lower()
        for pattern, responses in self.rules:
            match = re.search(pattern, user_input)
            if match:
                response = random.choice(responses).format(*match.groups())
                return response
        return random.choice(self.defaults)

if __name__ == "__main__":
    eliza = SimpleELIZA()
    print("ELIZA: Hello, I am ELIZA. How are you feeling today?")
    print("Type 'quit' to end.")
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            print("ELIZA: Goodbye.")
            break
        print(f"ELIZA: {eliza.get_response(user_input)}")