# -*- coding: utf-8 -*-
"""LLM Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzAZVg0ZhoFIUR5H2ETjHdiApGRIWvXv
"""

!pip install transformers torch accelerate

# Install required libraries (run this cell first in Colab)
!pip install transformers torch accelerate

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Use the correct conversational model
model_name = "microsoft/DialoGPT-medium"

print("Loading model...")
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Set padding token to avoid warnings
tokenizer.pad_token = tokenizer.eos_token

def get_llm_response(user_input, chat_history_ids=None):
    """Generate a proper conversational response."""

    new_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors='pt')


    if chat_history_ids is not None:
        bot_input_ids = torch.cat([chat_history_ids, new_input_ids], dim=-1)
    else:
        bot_input_ids = new_input_ids


    chat_history_ids = model.generate(
        bot_input_ids,
        max_length=1000,
        pad_token_id=tokenizer.eos_token_id,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.75
    )


    response = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
    return response, chat_history_ids

print("\n--- Modern LLM Chatbot ---")
print("LLM: Hello, I am a modern conversational AI. How can I help you today?")
print("LLM: Type 'quit' to end the conversation.\n")

chat_history_ids = None
while True:
    user_input = input("You: ")
    if user_input.lower() == "quit":
        print("LLM: Goodbye! It was a pleasure chatting with you.")
        break
    response, chat_history_ids = get_llm_response(user_input, chat_history_ids)
    print(f"LLM: {response}")